### ISSUE TITLE
Contributor pass not working on other device

### ISSUE THREAD

**Issue by sidamos** [archon810/androidpolice-public#82] opened 2017-06-12 20:11 UTC
#### Expected behavior
I bought a Contributor pass on my desktop PC and it works. 
When I load an AP page on my Chromebook, I don't want to see ads there, too.

#### Actual behavior
Shows ads on my Chromebook.

#### Steps to reproduce the problem
See above.

**Comment by archon810** [comment] 2017-06-12 20:48
@sidamos Are you sure you are logged into the same account on ChromeOS and the desktop PC? As long as you are, you should absolutely not be seeing ads.

If you are indeed logged in with the same Google account as you're using for Contributor, what do you see here when you go here on your Chrome OS https://contributor.google.com? 

Could you please share some screenshots? If we confirm there's indeed an issue, I can get Google involved.

**Comment by sidamos** [comment] 2017-06-13 17:50
Yes, I am signed into the same account. Attaching screenshots.

![chromebook1](https://user-images.githubusercontent.com/873537/27096490-8a1105b4-5071-11e7-8c83-6f9f11d9e43b.png)
![chromebook2](https://user-images.githubusercontent.com/873537/27096491-8a12c05c-5071-11e7-9168-88c830a6ef59.png)
![desktop1](https://user-images.githubusercontent.com/873537/27096492-8a141510-5071-11e7-9902-c904da71eea8.png)
![desktop2](https://user-images.githubusercontent.com/873537/27096493-8a177c6e-5071-11e7-8759-5416efa7f619.png)

**Comment by sidamos** [comment] 2017-06-13 17:53
BTW, on the desktop, without the ads, the page could use more of the available space in width.

**Comment by archon810** [comment] 2017-06-13 19:13
@sidamos I've passed this directly to the Google Funding Choices team. Thanks.

**Comment by archon810** [comment] 2017-06-14 01:54
@sidamos I heard back from Google. They can't reproduce this and need more info from you, if you're willing to work with them.

Can you please report the issue to them directly using https://support.google.com/contributor/answer/7302081?

Also please let them know if you're using the Google multi-login and what extensions you have installed.

I'll close this for now as it's out of our hands, but do post a comment if you get it figured out in the future.

**Closed by archon810** 2017-06-14 01:54 UTC
